# Generated by Django 2.1.7 on 2019-02-23 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app_info',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pwd', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='app_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskType', models.IntegerField()),
                ('taskStatus', models.IntegerField()),
                ('lon', models.FloatField(default=0.0)),
                ('lat', models.FloatField(default=0.0)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoDriver.app_info')),
            ],
        ),
        migrations.CreateModel(
            name='task_info',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('startlon', models.FloatField(default=0.0)),
                ('startlat', models.FloatField(default=0.0)),
                ('endlon', models.FloatField(default=0.0)),
                ('endlat', models.FloatField(default=0.0)),
                ('transferPoints', models.TextField(default='[]')),
                ('path', models.TextField(default='[]')),
                ('current_task', models.BooleanField(default=True)),
                ('taskType', models.IntegerField(default=0)),
                ('taskStatus', models.IntegerField(default=0)),
                ('endStatus', models.IntegerField(default=0)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoDriver.app_info')),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_info',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=True)),
                ('vehicleType', models.FloatField(default=0.0)),
                ('battery', models.FloatField(default=0.0)),
                ('carNum', models.TextField()),
                ('camera', models.BooleanField(default=True)),
                ('lidar', models.BooleanField(default=True)),
                ('radar', models.BooleanField(default=True)),
                ('rtk', models.BooleanField(default=True)),
                ('px2', models.BooleanField(default=True)),
                ('ipc', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('lon', models.FloatField(default=0.0)),
                ('lat', models.FloatField(default=0.0)),
                ('taskType', models.IntegerField()),
                ('taskStatus', models.IntegerField()),
                ('velocity', models.FloatField(default=0.0)),
                ('direction', models.FloatField(default=0.0)),
                ('estimateTime', models.FloatField(default=0.0)),
                ('odometry', models.FloatField(default=0.0)),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoDriver.vehicle_info')),
            ],
        ),
        migrations.AddField(
            model_name='task_info',
            name='vid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoDriver.vehicle_info'),
        ),
    ]
