# Generated by Django 2.1.7 on 2019-03-06 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app_info',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pwd', models.TextField()),
                ('p_type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='app_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(default=0.0)),
                ('lat', models.FloatField(default=0.0)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoDriver.app_info')),
            ],
        ),
        migrations.CreateModel(
            name='task_info',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('start_lon', models.FloatField(default=0.0)),
                ('start_lat', models.FloatField(default=0.0)),
                ('end_lon', models.FloatField(default=0.0)),
                ('end_lat', models.FloatField(default=0.0)),
                ('transfer_points', models.TextField(default='[]')),
                ('path', models.TextField(default='[]')),
                ('current_task', models.BooleanField(default=True)),
                ('task_type', models.IntegerField(default=0)),
                ('task_status', models.IntegerField(default=0)),
                ('end_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_info',
            fields=[
                ('vehicle_type', models.FloatField(default=0.0)),
                ('car_num', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(default=0.0)),
                ('lat', models.FloatField(default=0.0)),
                ('available', models.BooleanField(default=True)),
                ('battery', models.FloatField(default=0.0)),
                ('estimate_time', models.FloatField(default=0.0)),
                ('odometry', models.FloatField(default=0.0)),
                ('have_task', models.BooleanField(default=False)),
                ('car_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoDriver.vehicle_info')),
            ],
        ),
        migrations.AddField(
            model_name='task_info',
            name='car_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoDriver.vehicle_info'),
        ),
        migrations.AddField(
            model_name='task_info',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoDriver.app_info'),
        ),
    ]
