# Generated by Django 2.1.7 on 2019-03-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoDriver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_info',
            name='end_time',
            field=models.TextField(default='0'),
        ),
    ]
