# Generated by Django 2.1.5 on 2019-03-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoDriver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_info',
            name='current_task',
            field=models.IntegerField(default=0),
        ),
    ]
