# Generated by Django 2.1.7 on 2019-03-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoDriver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_task',
            name='car_num',
        ),
        migrations.AddField(
            model_name='vehicle_info',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle_info',
            name='battery',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vehicle_info',
            name='estimate_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vehicle_info',
            name='have_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle_info',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vehicle_info',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vehicle_info',
            name='odometry',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='vehicle_task',
        ),
    ]
