# Generated by Django 2.1.7 on 2019-02-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoDriver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_info',
            name='tel',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
