# Generated by Django 2.1.7 on 2019-03-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoDriver', '0002_auto_20190306_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_info',
            name='vehicle_type',
            field=models.IntegerField(default=1),
        ),
    ]
