# Generated by Django 2.1.7 on 2019-02-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoDriver', '0002_app_info_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app_info',
            name='tel',
        ),
        migrations.AlterField(
            model_name='app_info',
            name='pid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
