# Generated by Django 2.1.7 on 2019-03-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoDriver', '0003_auto_20190306_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_info',
            name='available',
            field=models.IntegerField(default=0),
        ),
    ]
