# Generated by Django 2.1.7 on 2019-03-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoDriver', '0004_auto_20190306_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_info',
            name='have_task',
            field=models.IntegerField(default=0),
        ),
    ]
