# Generated by Django 2.1.5 on 2019-03-11 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoDriver', '0002_auto_20190307_0941'),
        ('autoDriver', '0005_auto_20190310_1248'),
    ]

    operations = [
    ]
