# Generated by Django 2.1.7 on 2019-03-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoDriver', '0006_app_task_have_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='end_task_info',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='task_info',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
