# Generated by Django 2.1.7 on 2019-03-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoDriver', '0006_auto_20190306_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_info',
            name='pid',
            field=models.IntegerField(default=0),
        ),
    ]
