# Generated by Django 2.1.7 on 2019-03-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoDriver', '0012_auto_20190311_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_info',
            name='path',
            field=models.TextField(default=[]),
        ),
    ]
