# Generated by Django 2.1.5 on 2019-03-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoDriver', '0013_auto_20190311_1549'),
        ('autoDriver', '0006_merge_20190311_0153'),
    ]

    operations = [
    ]
