# Generated by Django 2.1.7 on 2019-04-16 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoDriver', '0015_auto_20190415_1335'),
        ('autoDriver', '0015_auto_20190401_1106'),
    ]

    operations = [
    ]
