# Generated by Django 2.1.7 on 2019-04-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoDriver', '0016_merge_20190416_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_task',
            name='task_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='app_task',
            name='task_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task_info',
            name='app_park_enable_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task_info',
            name='car_park_enable_status',
            field=models.IntegerField(default=0),
        ),
    ]
